kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: rover-scc # SCC NAME
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 1002
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 1000
supplementalGroups:
  type: MustRunAs
  ranges:
  - min: 1000
    max: 1000
users:
- rover-sa   # service account name
